### ISSUE TITLE
게임 시작할때 이벤트 하나만

### ISSUE THREAD

**Issue by r4pidstart** [pooh-transcendence/backend#125]
**📝 DESCRIPTION**

- Date : 2023.07.

**☑ TODO**

- [ ]

게임 시작해야 레디창을 없앨 수 있는데 그게 없는 것 가틈..

**Comment by ghonman2** [comment]
프론트가 받는 거 말씀하시는 거면 gameReady로 받으시면 됩니다. 실제로 시작할 때는 gameReadyDto라는 이벤트로 시작합니다

**Comment by ghonman2** [comment]
그럼 보내실 이벤트 이름 알려주세요 그럼 그대로 만들겠습니다

**Comment by r4pidstart** [comment]
gameReadyDto 이거 아니예요?
만드실거면 gameStart로 만들어주세요

**Comment by r4pidstart** [comment]
그거 제가만든거임
백쪽에서만 보내면 알아서 돌아가요

**Comment by ghonman2** [comment]
gameStart 라는 걸 백에서 받길 원하는 거에요? 아님 프론트에서 받길 원하시는 건가요 ?

**Comment by r4pidstart** [comment]
양쪽 레디 끝나고 게임 시작할 때 프론트로 보내주세요

**Comment by r4pidstart** [comment]
이름 겹치면 맘대로 바꾸셔도 상관없고

**Comment by r4pidstart** [comment]
아녀요 제가바꿈
