### ISSUE TITLE
클라이언트가 받을 이벤트

### ISSUE THREAD

**Issue by ghonman2** [pooh-transcendence/backend#50]
**📝 DESCRIPTION**

- Date : 2023.07.

**Comment by r4pidstart** [comment]
채널 관리자 리스트 조회할 수 있는거 필요해요

**Comment by r4pidstart** [comment]
채널 만들어진 이후에 초대할 수 있는 방법좀 만들어주세요

**Comment by r4pidstart** [comment]
모든 유저를 조회할 수 있는 방법이 필요해요

**Comment by ghonman2** [comment]
> 채널 만들어진 이후에 초대할 수 있는 방법좀 만들어주세요

joinChannel 로 채널이 만들어진 이후에 초대하는 기능이 있습니다 .

**Comment by ghonman2** [comment]
> 필요해요
네넵 구현했습니다

**Comment by ghonman2** [comment]
> 채널 관리자 리스트 조회할 수 있는거 필요해요

네넵 구현했습니다

**Comment by r4pidstart** [comment]
visibleChannelList

ownerNickname이랑, 채널에 존재하는 인원 수 같이 좀 보내주셨으면 좋겠습니다.

**Comment by yubinquitous** [comment]
오늘 안에 추가하겠습니다 ~

**Comment by yubinquitous** [comment]
> visibleChannelList
> 
> ownerNickname이랑, 채널에 존재하는 인원 수 같이 좀 보내주셨으면 좋겠습니다.

완료하고 노션 문서 수정했습니다~

**Comment by r4pidstart** [comment]
친구추가에 필요한데 가입된 모든 유저 조회하는 기능좀 부탁드려요

**Comment by ghonman2** [comment]
> 친구추가에 필요한데 가입된 모든 유저 조회하는 기능좀 부탁드려요

이거 allUser 라는 event로 던져주기면 됩니다. rest는 get으로 던져주시고 socketio는  /channel입니다

**Comment by r4pidstart** [comment]
이거 지금 구현은 안 된거죠? 
[Nest] 52  - 08/14/2023, 1:01:39 AM     LOG [HTTP] /allUser
[Nest] 52  - 08/14/2023, 1:01:42 AM     LOG [HTTP] ::ffff:172.20.0.1 GET 404

**Comment by ghonman2** [comment]
> 이거 지금 구현은 안 된거죠? [Nest] 52 - 08/14/2023, 1:01:39 AM LOG [HTTP] /allUser [Nest] 52 - 08/14/2023, 1:01:42 AM LOG [HTTP] ::ffff:172.20.0.1 GET 404

아뇨 구현 되어있있습니다. /user/AllUser입니다

**Comment by r4pidstart** [comment]
/user/AllUser랑 /user/allUser 둘다 400떠요

{
    "data": {
        "success": false,
        "timestamp": "2023-08-14T01:19:06.055Z",
        "message": "Validation failed (numeric string is expected)",
        "error": "Bad Request",
        "statusCode": 400
    },
    "status": 400,
    "statusText": "Bad Request",
    "headers": {
        "content-length": "154",
        "content-type": "application/json; charset=utf-8"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibmlja25hbWUiOiJ0ZXN0MiIsImZ0SWQiOiJ0am9hc2RmIiwiaWF0IjoxNjkxOTcyODc1LCJleHAiOjE2OTQ1NjQ4NzV9.hMSX82U4JZtvw9QpXyDpXI5jIwDsKIDKIbQ3uLKYbnk"
        },
        "method": "get",
        "url": "http://localhost:3000/user/AllUser"
    },
    "request": {}
}

그거랑 지금 소켓쪽 연결만 되고 친구목록이건 뭐건 emit 보내도 ack도 안 오는거 보면 작동 안 되는 것 같은데 확인좀 해주시겠어요

**Comment by ghonman2** [comment]
> /user/AllUser랑 /user/allUser 둘다 400떠요

다시 한번 해보시죠

**Comment by r4pidstart** [comment]
AllUser는 잘 되는데, 소켓이 여전히 고장나있네요 이따 보시죠

**Comment by ghonman2** [comment]
close(#50)
