### ISSUE TITLE
block api 작동 안 함

### ISSUE THREAD

**Issue by r4pidstart** [pooh-transcendence/backend#61]
**📝 DESCRIPTION**

- Date : 2023.08.11

 const blockHandler=() => {console.log("block", state.chatTargetUser); api_post("/block", {"bannedUserId": state.chatTargetUser})}; 

returns
{
    "message": "Request failed with status code 400",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 400\n    at settle (webpack-internal:///(app-client)/./node_modules/axios/lib/core/settle.js:24:12)\n    at XMLHttpRequest.onloadend (webpack-internal:///(app-client)/./node_modules/axios/lib/adapters/xhr.js:121:66)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json",
            "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibmlja25hbWUiOiJoZWxsbzIiLCJmdElkIjoiam9vd3Bhcmsyc3RkdWVudC5zZW91bC5rciIsImlhdCI6MTY5MTQ2MDE3MiwiZXhwIjoxNjk0MDUyMTcyfQ.mAWRJ_UMpeDQ1zHPX5V4K3q2E63-OuptuViqWeIcEuA"
        },
        "method": "post",
        "url": "http://localhost:3000/block",
        "data": "{\"bannedUserId\":2}"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 400
}

그거랑 소켓으로 들어오는 요청도 콘솔에 로그좀 찍히게 해주세요
대부분 아무것도 안 떠서 너무 힘드러

**Comment by ghonman2** [comment]
이 api 도 잘 작동하는 것을 확인했습니다. 아마 api_post의 return 이 promise 인데 아마 await로 해서 값을 받으면 괜찮을 것 같습니다. 안되면 다시 고쳐보죠

**Comment by yubinquitous** [comment]
```
socket.emit('your_event', { someData: 'example' }, (response) => {
  console.log('ACK received:', response); // here!
});
```

이런식으로 로그찍어주시는거 맞나영 ?
