### ISSUE TITLE
channel 생성 안 됨

### ISSUE THREAD

**Issue by r4pidstart** [pooh-transcendence/backend#62]
**📝 DESCRIPTION**

- Date : 2023.08.11

localhost:3000/channel에 

{
    "channelInfo": {
        "channelType": "PUBLIC",
        "channelName": "ch1",
        "ownerId": 2,
    },
    "channelUserIds": [
        1, 2,
    ]
}
로 post했는데

{
    "success": false,
    "timestamp": "2023-08-10T20:59:42.796Z",
    "message": "Validation failed (numeric string[] is expected)",
    "error": "Bad Request",
    "statusCode": 400
}
가 떠요

**Comment by ghonman2** [comment]
json 형태가 잘못 보내셔서 에러가 난 것 같습니다.

``` json
{
     "channelInfo": {
           "channelType": "PUBLIC",
           "channelName": "ch1",
           "ownerId": 2
     },
          "channelUserIds": [1, 2]
} 
``` 

이렇게 집어 넣어보고 안되면 말씀해주세요
