### ISSUE TITLE
/auth/accessToken http 500

### ISSUE THREAD

**Issue by r4pidstart** [pooh-transcendence/backend#69]
**📝 DESCRIPTION**

- Date : 2023.07.

**☑ TODO**

- [ ]

{
    "data": {
        "statusCode": 500,
        "message": "Internal server error"
    },
    "status": 500,
    "statusText": "Internal Server Error",
    "headers": {
        "content-length": "52",
        "content-type": "application/json; charset=utf-8"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json",
            "Authorization": "Bearer null"
        },
        "method": "post",
        "url": "http://localhost:3000/auth/accessToken",
        "data": "{\"id\":1}"
    },
    "request": {}
}

[Nest] 52  - 08/13/2023, 10:28:43 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'split')
TypeError: Cannot read properties of undefined (reading 'split')
    at AuthController.getAccessToken (/app/src/auth/auth.controller.ts:58:8)
    at /app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Nest] 52  - 08/13/2023, 10:28:43 AM     LOG [HTTP] ::ffff:172.20.0.1 POST 500
[Nest] 52  - 08/13/2023, 10:28:43 AM     LOG [HTTP] /auth/accessToken

그거랑 별개로, qr스캔할때마다 계속 번호가 하나씩 추가되는데 한 번 추가해둔거 그대로 쓸 순 없는건가요?

**Comment by yubinquitous** [comment]
쿠키에 refreshToken이 없어서 발생하는 문제 같습니다!

**Comment by r4pidstart** [comment]
그렇다면 제가 무엇을 해야하오리까

**Comment by ghonman2** [comment]
처음에 받은 refreshtoken을 쿠키로 가지고 있어야합니다
 그래서 새팅해서 보냈는 데 확인 부탁드립니다

**Comment by r4pidstart** [comment]
쿠키를 제가 넣어야 하는 것입니까

**Comment by ghonman2** [comment]
일단은 저는 넣었습니다

**Comment by r4pidstart** [comment]
브라우저에서 qr 찍고 2차인증 된 상태예요.
signInWithVerificationCode까지 완료한 이후에요.
여러번해봐도 동일한

**Comment by ghonman2** [comment]
> 브라우저에서 qr 찍고 2차인증 된 상태예요. signInWithVerificationCode까지 완료한 이후에요. 여러번해봐도 동일한

혹시 개발자 도구에서 signInWithVerificationCode까지 완료해서 받은 데이터롤 보시면 refreshtoken이 세팅 되었는 지 확인 부탁드립니다. 이때 아마 token을 못 볼 텐데 일단 처리 안되면 낼 보죠

**Comment by r4pidstart** [comment]
<img width="868" alt="image" src="https://github.com/pooh-transcendence/backend/assets/67845112/8c164282-b214-4624-b155-b7ba2769322a">

일단 쿠키창엔 아무것도 안 보여요
일단 프론트쪽에서 인증부분은 끝났는데, 레포에 올려둘테니 직접 해보시고 함 확인해보셔요
api secret key 바뀌여서 env 레포 땡겨오시고 frontend 다시 빌드하셔야될겁니다 재시작하는걸론 환경변수가 안바뀌는것같은데 확실히는 모름
