### ISSUE TITLE
클라이언트 이벤트 list

### ISSUE THREAD

**Issue by ghonman2** [pooh-transcendence/backend#75]
**📝 DESCRIPTION**

- Date : 2023.07.

**☑ TODO**

- [ ]

**Comment by r4pidstart** [comment]
/user/channel에 채널 참가자 목록이나, 채널 참가자 인원수 둘 중 하나 편한거 같이 좀 보내주십셩

**Comment by yubinquitous** [comment]
유저 수가 필요하다고 하셔서 채널에 속한 유저 수를 response data에 추가했습니다~ 노션도 수정 완 ~

**Comment by ghonman2** [comment]
getFriendList
getBlockList
visibleChannel,
user/channelList
에다가 쏴주면 될까요 ?

**Comment by r4pidstart** [comment]
네에 그럼 리스너 만들어서 리랜더 하는걸로 할게요
