### ISSUE TITLE
/user/:userid | 400 bad request

### ISSUE THREAD

**Issue by r4pidstart** [pooh-transcendence/backend#76]
**📝 DESCRIPTION**

- Date : 2023.07.

**☑ TODO**

<img width="676" alt="image" src="https://github.com/pooh-transcendence/backend/assets/67845112/0bd7c99e-7268-4700-a120-0418ccaaf38d">

<img width="350" alt="image" src="https://github.com/pooh-transcendence/backend/assets/67845112/08e77c24-98bd-49b3-acd5-66cb49e4537d">

뭔가 뭔가 잘못됐어요..

**Comment by yubinquitous** [comment]
방금 수정해서 메인에 머지했습니다~ api 라우팅에 문제가 좀 있었네여,,
